- name: Example Postbuild Playbook

  # Only configure the machines we gave the {ansible = webserver} label in the Terraform.
  hosts: label_ansible_webserver
  become: yes
  gather_facts: no
  tasks:

    # First step is always to wait for all machines in the group to come up in the case where
    # this playbook starts running before the machines do.
    - name: Wait for machine start
      wait_for_connection:
        timeout: 600 # ten minutes
      
    - name: Start nginx
      service:
        name: nginx
        state: started