# Deploy all pushes to non-qa and non-main branches to the development environment.
# author: @doughepi

on:
  push:
    branches-ignore:
      - qa
      - main
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    env:
      ORG_ID: "937800926639"
      PROJECT_ID: example-dev-4c39ae
      TF_BUCKET: 134926683163-tfstate
      SERVICE_ACCOUNT: github-workflow@example-dev-4c39ae.iam.gserviceaccount.com
      IMAGE_FAMILY: example-family
      IMAGE_NAME: example-image
      NETWORK_PROJECT_ID: network-prod-2a8575
      SUBNETWORK: general-purpose-computation-dev
      ZONE: us-central1-a
    steps:
      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install packer -y
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Commit Hash
        id: commit_hash
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.BUILD_KEY_DEV }}
          export_default_credentials: true
      - name: Packer Init
        run: packer init build/example.pkr.hcl
      - name: Packer Build
        run: |
          packer build -var "network_project_id=${{ env.NETWORK_PROJECT_ID }}" -var "project_id=${{ env.PROJECT_ID }}" \
          -var "image_family=${{ env.IMAGE_FAMILY }}" -var "image_name=${{ env.IMAGE_NAME }}" -var "subnetwork=${{ env.SUBNETWORK }}" \
          -var "zone=${{ env.ZONE }}" -var "service_account=${{ env.SERVICE_ACCOUNT }}" -var "commit_hash=${{ steps.commit_hash.outputs.sha_short }}" \
          build/example.pkr.hcl
    outputs:
      image_family: ${{ env.IMAGE_FAMILY }}
      image_name: ${{ env.IMAGE_NAME }}
      commit_hash: ${{ steps.commit_hash.outputs.sha_short }}

  infrastructure:
    name: "Infrastructure"
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      ORG_ID: "937800926639"
      PROJECT_ID: example-dev-4c39ae
      TF_BUCKET: 134926683163-tfstate
      SUBNETWORK: projects/network-prod-2a8575/regions/us-central1/subnetworks/general-purpose-computation-dev
    steps:
      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install terraform -y
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Commit Hash
        id: commit_hash
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.BUILD_KEY_DEV }}
          export_default_credentials: true
      - name: Terraform Init
        working-directory: ./infrastructure
        run: terraform init -backend-config="bucket=${{ env.TF_BUCKET }}"
      - name: Terraform Apply
        working-directory: ./infrastructure
        run: |
          terraform apply -auto-approve -no-color -var "org_id=${{ env.ORG_ID }}" -var "project_id=${{ env.PROJECT_ID }}" \
          -var "image_name=${{ needs.build.outputs.image_name }}" -var "commit_hash=${{ needs.build.outputs.commit_hash }}" \
          -var "subnetwork=${{ env.SUBNETWORK }}"
  postbuild:
    name: "Postbuild"
    runs-on: ubuntu-latest
    needs:
      - infrastructure
    env:
      PROJECT_ID: example-dev-4c39ae
      INVENTORY: inventory-dev.gcp.yml
    steps:
      - name: Install Ansible
        run: |
          pip install ansible google-auth
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.BUILD_KEY_DEV }}
          export_default_credentials: true

        # This should really be an action.
        # I can make that a TODO.
      - name: Configure oslogin
        id: oslogin
        working-directory: ./postbuild
        run: |
          ssh-keygen -t rsa -N "" -f id_rsa
          gcloud compute os-login ssh-keys add --key-file=id_rsa.pub --ttl 10m
          current=$(gcloud config get-value account)
          id=$(gcloud iam service-accounts describe $current --format='value(uniqueId)')
          echo "::set-output name=ansible_user::sa_${id}"

      - name: Run Ansible
        working-directory: ./postbuild/ansible
        run: |
          ansible-playbook -i $INVENTORY --extra-vars "ansible_user=${{ steps.oslogin.outputs.ansible_user }}" playbook.yml
